debug:
  hitbox: false
  exception: false
  pack: false
  tracker: false
module:
  model: true
  player-animation: true
pack:
  generate-modern-model: true
  generate-legacy-model: true
metrics: true
sight-trace: true
item: leather_horse_armor
max-sight: -1
min-sight: 5
lock-on-play-animation: false
namespace: "bettermodel"
pack-type: zip #folder, zip
build-folder-location: BetterModel/build
follow-mob-invisibility: true
animated-texture-frame-time: 10
create-pack-mcmeta: true
use-purpur-afk: true
version-check: true
default-mount-controller: walk
lerp-frame-time: 5
cancel-player-model-inventory: false
player-hide-delay: 3
packet-bundling-size: 16