name: Package plugin

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  build:
    if: github.actor == 'toxicity188'
    runs-on: ubuntu-latest
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      PACKAGES_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_NUMBER: ${{ github.run_number }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create Deployment
        id: deployment
        uses: actions/create-deployment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: production
          transient_environment: false
          description: "Publishing to GitHub Packages"
      - name: Publish package
        run: ./gradlew :api:publishAllPublicationToGitHubPackagesRepository --stacktrace
      - name: Set Deployment Status (success)
        if: success()
        uses: actions/deployment-status@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment.outputs.id }}
          state: success
          environment_url: https://github.com/toxicity188/BetterModel/packages
      - name: Set Deployment Status (failure)
        if: failure()
        uses: actions/deployment-status@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment.outputs.id }}
          state: failure
          environment_url: https://github.com/toxicity188/BetterModel/packages