name: Package plugin

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: github.actor == 'toxicity188'
    runs-on: ubuntu-latest
    env:
      PACKAGES_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      BUILD_NUMBER: ${{ github.run_number }}
      COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish package
        run: ./gradlew :api:publishAllPublicationToGitHubPackagesRepository --stacktrace